package pt.isel

import org.cojen.maker.ClassMaker
import org.cojen.maker.MethodMaker
import org.cojen.maker.Variable
import java.io.FileOutputStream
import kotlin.reflect.KClass
import kotlin.reflect.KParameter
import kotlin.reflect.full.findAnnotation
import kotlin.reflect.full.memberProperties

/**
 * index used as default getter value in the map (the first index)
 * if the map is empty, the code will fail during the newInstance method
 */
const val DEFAULT_GETTER_VALUE = "-0"

/**
 * A YamlParser that uses Cojen Maker to generate a parser.
 */
open class YamlParserCojen<T : Any>(
    private val type: KClass<T>,
    private val nrOfInitArgs: Int)
: AbstractYamlParser<T>(type) {

    companion object {
        private val primitiveType = setOf(
            Int::class,
            Char::class,
            Boolean::class,
            Long::class,
            Short::class,
            Byte::class,
            Double::class,
            Float::class,
            String::class
        )

        private val yamlParsers: MutableMap<String, YamlParserCojen<*>> = mutableMapOf()

        private fun parserName(type: KClass<*>, nrOfInitArgs: Int): String {
            return "YamlParser${type.simpleName}$nrOfInitArgs"
        }
        /**
         * Creates a YamlParser for the given type using Cojen Maker if it does not already exist.
         * Keep it in an internal cache.
         */
        fun <T : Any> yamlParser(type: KClass<T>, nrOfInitArgs: Int = type.constructors.first().parameters.size): AbstractYamlParser<T> {
            return yamlParsers.getOrPut(parserName(type, nrOfInitArgs)) {
                YamlParserCojen(type, nrOfInitArgs)
                    .buildYamlParser()
                    .finish()
                    .getConstructor(KClass::class.java, Int::class.java)
                    .newInstance(type, nrOfInitArgs) as YamlParserCojen<*>
            } as YamlParserCojen<T>
        }

        fun <T: Any> yamlParser(type: Class<T>, nrOfInitArgs: Int) : AbstractYamlParser<T> =
            yamlParser(type.kotlin, nrOfInitArgs)

        fun <T: Any> yamlParser(type: Class<T>) : AbstractYamlParser<T> =
            yamlParser(type.kotlin)

        fun <T: Any>testBuildMaker(type: KClass<T>, nrOfInitArgs: Int) {
            val cm = YamlParserCojen(type, nrOfInitArgs).buildYamlParser()
            cm.finishTo(FileOutputStream("YamlParserCojenDummy.class"))
        }
    }
    /**
     * Used to get a parser for other Type using the same parsing approach.
     */
    override fun <T : Any> yamlParser(type: KClass<T>) = YamlParserCojen.yamlParser(type)

    /**
     * Do not change this method in YamlParserCojen.
     */
    override fun newInstance(args: Map<String, Any>): T {
        throw UnsupportedOperationException("This method is overridden in a subclass dynamically generated by buildYamlParser() function!")
    }

    /**
     * Builds the YamlParser using Cojen Maker.
     * representation of the class in java :
     *
     *
     *      public class YamlParserCojenDummy implements YamlParserCojen<T> {
     *          private final Ktype<T> type;
     *          private final int nrOfInitArgs;
     *
     *          public YamlParserCojen(KClass<T> type, int nrOfInitArgs) {
     *              super (type, nrOfInitArgs);
     *              this.type = type;
     *              this.nrOfInitArgs = nrOfInitArgs;
     *          }
     *          public T newInstance(Map<String, Any> args) {
     *              /*
     *                  take the first constructor with the same number of arguments
     *                  as nrOfInitArgs
     *                  and create a new instance of the type with the arguments in the map
     *              */
     *          }
     *
     *          public T parseObject(Reader yaml) {...}
     *
     *          public List<T> parseList(Reader yaml) {...}
     *
     *          public YamlParser<T> yamlParser(KClass<T> type) {...}
     *      }
     */
    private fun buildYamlParser() : ClassMaker {
        // create the ClassMaker
        val cm = ClassMaker
            .begin()
            .public_()
            .extend(YamlParserCojen::class.java)
        // create the type field
        val fieldType = cm
            .addField(KClass::class.java, "type")
            .private_()
            .final_()
        // create the nrOfInitArgs field
        val fieldNrOfInitArgs = cm
            .addField(Int::class.java, "nrOfInitArgs")
            .private_()
            .final_()
        // add the constructor to the class
        val init = cm
            .addConstructor(KClass::class.java, Int::class.java)
            .public_()
        init
            .field(fieldType.name())
            .set(init.param(0))
        init
            .field(fieldNrOfInitArgs.name())
            .set(init.param(1))
        // call the superclass constructor and set the parameters
        init
            .invokeSuperConstructor(init.param(0), init.param(1))
        // add the newInstance method to the class
        val methodNewInstance = cm
            .addMethod(Any::class.java, "newInstance", Map::class.java)
            .public_()
            .override()
        buildNewInstanceMethod(methodNewInstance, nrOfInitArgs)

        return cm
    }

    private fun buildNewInstanceMethod(
        method: MethodMaker,
        nrOfInitArgs: Int
    ) {
        if (type in primitiveType) {
            method.return_(method.param(0).invoke("get", ""))
            return
        }

        val javaConstructor =
            type
                .java
                .constructors
                .first {
                    it.parameters.size == nrOfInitArgs
                }

        val constructorKParameters =
            type
                .constructors
                .first()
                .parameters

        /**
         * A map with the parameters of the constructor and the corresponding KParameter
         */
        val parameters =
            javaConstructor
                .parameters
                .map { it to constructorKParameters.first { kP -> kP.name == it.name } }

        val mP =
            type
                .memberProperties
                .filter {
                    parameters
                        .any {
                            (p, _)->
                            it.name == p.name && (it.returnType.classifier as KClass<*>).java == p.type
                        }
                }

        val yamlConvert = hashMapOf<String, YamlConvert>()
        val yamlArg = hashMapOf<String, String>()

        mP.forEach {
            val scrName = it.findAnnotation<YamlArg>()?.scrName
            val cVert: YamlConvert? = it.findAnnotation<YamlConvert>()
            scrName?.let { scrN ->
                yamlArg[it.name] = scrN
                cVert?.let{ cV ->
                    yamlConvert[it.name] = cV
                }
            } ?: run {
                cVert?.let { cV ->
                    yamlConvert[it.name] = cV
                }
            }
        }

        val args = method
            .param(0)

        val argsList = parameters.map { (param, kParam) ->
            val value = args
                .invoke("get", param.name)
            value.ifEq(null) {
                value.set(
                    args.invoke("get", yamlArg[param.name])
                )
            }

            val convert = yamlConvert[param.name]
            if (convert != null) {
                method.new_(convert.converter.java)
                    .invoke("strConverter", value.cast(String::class.java))
            } else {
                typeOf(method, param.type, value, kParam)
            }
        }.toTypedArray()

        val retObj = method.new_(type.java, *argsList)

        method.return_(retObj)
    }

    private fun typeOf(
        method: MethodMaker,
        cClass: Class<*>,
        v: Variable,
        kParam: KParameter,
    ): Variable {
        return when(cClass) {
            Int::class.java -> typeParser(method, v, Int::class.java, "parseInt")
            Char::class.java -> v.invoke("charAt", 0)
            Boolean::class.java -> typeParser(method, v, Boolean::class.java, "parseBoolean")
            Long::class.java -> typeParser(method, v, Long::class.java, "parseLong")
            Short::class.java -> typeParser(method, v, Short::class.java, "parseShort")
            Byte::class.java -> typeParser(method, v, Byte::class.java, "parseByte")
            Double::class.java -> typeParser(method, v, Double::class.java, "parseDouble")
            Float::class.java -> typeParser(method, v, Float::class.java, "parseFloat")
            String::class.java -> v.cast(String::class.java)
            else -> {
                if (cClass == List::class.java) {
                    val kType =
                        kParam
                            .type
                            .arguments
                            .firstOrNull()
                            ?.type
                            ?.classifier as KClass<*>

                    if (kType !in primitiveType) {
                        method
                            .`var`(YamlParserCojen::class.java)
                            .field("Companion")
                            .invoke(
                                "yamlParser",
                                kType.java,
                                v.cast(Map::class.java)
                                    .invoke("get", DEFAULT_GETTER_VALUE)
                                    .cast(Map::class.java)
                                    .invoke("size")
                                    .cast(Int::class.java)
                            ).invoke(
                                "typeReturn",
                                v.cast(Map::class.java)
                            ).cast(cClass)
                    } else {
                        method
                            .`var`(YamlParserCojen::class.java)
                            .field("Companion")
                            .invoke(
                                "yamlParser",
                                kType.java
                            )
                            .invoke(
                                "typeReturn",
                                v.cast(Map::class.java)
                            ).cast(cClass)
                    }
                }
                else {
                    method.`var`(YamlParserCojen::class.java)
                        .field("Companion")
                        .invoke("yamlParser", cClass,
                            v
                            .cast(Map::class.java)
                            .invoke("size")
                            .cast(Int::class.java))
                        .invoke("newInstance", v.cast(Map::class.java))
                        .cast(cClass)
                }
            }
        }
    }

    private fun typeParser(method: MethodMaker, v: Variable, type: Class<*>, func: String): Variable =
        method
            .`var`(type)
            .invoke(func, v.cast(String::class.java))
}
